version: "3.9"
services:
  api-gateway:
    build: .
    ports:
      - 80:3000
    restart: unless-stopped
    environment: 
      PORT:              3000
      RABBITMQ_URL:      ${RABBITMQ_URL:?RABBITMQ_URL is missing}
    logging:
      driver: awslogs
      options:
        awslogs-region: ${LOG_REGION:?LOG_REGION is missing}
        awslogs-group:  ${LOG_GROUP:?LOG_GROUP is missing}
        mode:           non-blocking
